# Generated by Django 4.2 on 2024-03-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_contmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_content_manager',
            field=models.BooleanField(default=False, verbose_name='контент-менеджер'),
        ),
        migrations.DeleteModel(
            name='ContManager',
        ),
    ]
