# Generated by Django 5.0.3 on 2024-03-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='product_name',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='version_number',
        ),
    ]
