# Generated by Django 5.0.3 on 2024-03-23 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_product_name_version_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='продукт'),
        ),
    ]
