# Generated by Django 5.0.2 on 2024-02-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_blogwriting_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogwriting',
            options={'verbose_name': 'блог', 'verbose_name_plural': 'блоги'},
        ),
    ]
