# Generated by Django 5.0.2 on 2024-02-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_blogwriting_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogwriting',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='slug'),
        ),
    ]
