# Generated by Django 4.2 on 2024-03-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_options_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogwriting',
            options={'permissions': [('set_published', 'Can publish blogs')], 'verbose_name': 'блог', 'verbose_name_plural': 'блоги'},
        ),
    ]
